version: '3.8'

services:
  db:
    image: postgres
    restart: always
    container_name: notifications-service-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=notifications-service
      - POSTGRES_DATA=data/postgres
    volumes:
      - ./data/pg:/data/postgres
    networks:
      - notifications-service-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notifications-service-api
    ports:
      - '8080:8080'
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - notifications-service-network

networks:
  notifications-service-network:
    driver: bridge